
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_GameManager from "./scripts/GameManager";
import * as scripts_Player from "./scripts/Player";
import * as scripts_BlockManager from "./scripts/BlockManager";

export const scriptsMap = {
    "scripts/GameManager.ts": scripts_GameManager,
	"scripts/Player.ts": scripts_Player,
	"scripts/BlockManager.ts": scripts_BlockManager
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
